<?php

namespace AppBundle\Repository;

/**
 * DossierMedicalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DossierMedicalRepository extends \Doctrine\ORM\EntityRepository
{
}
