<?php

namespace AppBundle\Repository;

/**
 * FicheMedicalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheMedicalRepository extends \Doctrine\ORM\EntityRepository
{
}
